[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
  "crates/*",
]

[dependencies]
boba_core = { path = "./crates/boba_core" }
boba_3d = { path = "./crates/boba_3d" }
milk_tea = { path = "./crates/milk_tea" }
taro_core = { path = "./crates/taro_core" }
boba_rapier3d = { path = "./crates/boba_rapier3d" }
taro_deferred_pipeline = { path = "./crates/taro_deferred_pipeline" }
taro_milk_tea = { path = "./crates/taro_milk_tea" }
