[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
  "crates/*",
]

[dependencies]
boba_core = { path = "./crates/boba_core" }
boba_3d = { path = "./crates/boba_3d" }
milk_tea = { path = "./crates/milk_tea" }
boba_rapier3d = { path = "./crates/boba_rapier3d" }
taro_renderer = { path = "./crates/taro_renderer" }
taro_standard_adapters = { path = "./crates/taro_standard_adapters" }
taro_standard_shaders = { path = "./crates/taro_standard_shaders" }
