[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
  "crates/*",
]

[dependencies]
handle_map = { path = "./crates/handle_map" }
boba_hybrid = { path = "./crates/boba_hybrid" }
milk_tea_manager = { path = "./crates/milk_tea_manager" }
