[package]
name = "milk_tea"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
winit = "0.28"
anyhow = "1.0"
indexmap = "1.9"
env_logger = "0.10"
raw-window-handle = "0.5"

boba_core = { path = "../boba_core" }
