[package]
name = "boba_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "1.9"
thiserror = "1.0"
once_cell = "1.17"
hashbrown = "0.13"

reterse = { path = "../reterse" }
imposters = { path = "../imposters" }
