[package]
name = "boba_rapier3d"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
rapier3d = "0.16"
nalgebra = { version = "0.31", features = ['convert-glam022']}

boba_core = { path = "../boba_core" }
boba_3d = { path = "../boba_3d" }
