[package]
name = "taro_milk_tea"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"

boba_core = { path = "../boba_core" }
milk_tea = { path = "../milk_tea" }
taro_core = { path = "../taro_core" }
